/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: chunk.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./chunk_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.FileServerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.FileServerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Request,
 *   !proto.Chunk>}
 */
const methodDescriptor_FileServer_download = new grpc.web.MethodDescriptor(
  '/FileServer/download',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.Request,
  proto.Chunk,
  /**
   * @param {!proto.Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Chunk.deserializeBinary
);


/**
 * @param {!proto.Request} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.Chunk>}
 *     The XHR Node Readable Stream
 */
proto.FileServerClient.prototype.download =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/FileServer/download',
      request,
      metadata || {},
      methodDescriptor_FileServer_download);
};


/**
 * @param {!proto.Request} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.Chunk>}
 *     The XHR Node Readable Stream
 */
proto.FileServerPromiseClient.prototype.download =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/FileServer/download',
      request,
      metadata || {},
      methodDescriptor_FileServer_download);
};


module.exports = proto;

