/**
 * @fileoverview gRPC-Web generated client stub for mmio
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: mmio.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.mmio = require('./mmio_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.mmio.MMIOClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.mmio.MMIOPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.mmio.WriteRequest,
 *   !proto.mmio.WriteReply>}
 */
const methodDescriptor_MMIO_write = new grpc.web.MethodDescriptor(
  '/mmio.MMIO/write',
  grpc.web.MethodType.UNARY,
  proto.mmio.WriteRequest,
  proto.mmio.WriteReply,
  /**
   * @param {!proto.mmio.WriteRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.mmio.WriteReply.deserializeBinary
);


/**
 * @param {!proto.mmio.WriteRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.mmio.WriteReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.mmio.WriteReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.mmio.MMIOClient.prototype.write =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/mmio.MMIO/write',
      request,
      metadata || {},
      methodDescriptor_MMIO_write,
      callback);
};


/**
 * @param {!proto.mmio.WriteRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.mmio.WriteReply>}
 *     Promise that resolves to the response
 */
proto.mmio.MMIOPromiseClient.prototype.write =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/mmio.MMIO/write',
      request,
      metadata || {},
      methodDescriptor_MMIO_write);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.mmio.ReadRequest,
 *   !proto.mmio.ReadReply>}
 */
const methodDescriptor_MMIO_read = new grpc.web.MethodDescriptor(
  '/mmio.MMIO/read',
  grpc.web.MethodType.UNARY,
  proto.mmio.ReadRequest,
  proto.mmio.ReadReply,
  /**
   * @param {!proto.mmio.ReadRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.mmio.ReadReply.deserializeBinary
);


/**
 * @param {!proto.mmio.ReadRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.mmio.ReadReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.mmio.ReadReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.mmio.MMIOClient.prototype.read =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/mmio.MMIO/read',
      request,
      metadata || {},
      methodDescriptor_MMIO_read,
      callback);
};


/**
 * @param {!proto.mmio.ReadRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.mmio.ReadReply>}
 *     Promise that resolves to the response
 */
proto.mmio.MMIOPromiseClient.prototype.read =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/mmio.MMIO/read',
      request,
      metadata || {},
      methodDescriptor_MMIO_read);
};


module.exports = proto.mmio;

